default:
    trainer: sac
    time_horizon: 2048
    batch_size: 128
    buffer_size: 1000000
    buffer_init_steps: 10000
    init_entcoef: 0.25
    train_interval: 3
    num_update: 1
    tau: 0.005
    hidden_units: 1024
    learning_rate: 1e-4
    num_layers: 2
    beta: 1.0e-2
    max_steps: 3.0e6
    use_recurrent: false
    num_epoch: 3
    sequence_length: 64
    memory_size: 256
    summary_freq: 1000
    learning_rate_schedule: constant
    normalize: false
    vis_encode_type: resnet
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.01
            gamma: 0.99
            encoding_size: 256